name          'abuxton-puppet_audit'
version       '0.1.0'
source        'https://github.com/abuxton/puppet_audit'
author        'abuxton'
license       'Apache 2.0'
summary       'A simple puppet module to fill the gap left by puppet audit meta param. handled file, directory and link as defined types, exposed to hiera data for create resources.'
description   ''
project_page  'https://github.com/abuxton/puppet_audit'

dependency 'puppetlabs/stdlib'
